version: 2.1
orbs:
    singularity: singularity/singularity@1.0.8

jobs:

  build_sif:
    docker:
    - image: singularityware/singularity:3.2.1-slim
    steps:
    - checkout
    - attach_workspace:
        at: /tmp/workspace
    - run:
        name: Building singularity image from docker tar
        no_output_timeout: 1h
        command: |
          singularity build /tmp/singularity_image.sif docker-archive:///tmp/workspace/docker_image.tar
    - persist_to_workspace:
        root: /tmp
        paths:
        - singularity_image.sif
        
        
  #running a singularity requires a machine executor, not docker..
  test_sif:
    machine: true
    steps:

    # set-up machine with singularity
    
      - singularity/install-go
      - run:
         name: Update repo
         command: |
           sudo apt-get update
      - singularity/debian-install-3

    # get singularity image from workspace
    
      - attach_workspace:
         at: /tmp/workspace

    # run tests:
      - run:
         name: Testing singularity image with exec
         no_output_timeout: 1h
         command: |
           singularity exec /tmp/workspace/singularity_image.sif ls
           
  build_docker:
    docker:
    - image: docker:17.05.0-ce-git
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Building Docker container
        no_output_timeout: 1h
        command: |
          if [ "$CIRCLE_BRANCH" = "master" -o "$CIRCLE_BRANCH" = "" ]; then MY_TAG=latest; else MY_TAG=$CIRCLE_BRANCH; fi
          export DOCKER_NAME=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$MY_TAG
          docker build -t $DOCKER_NAME .
          docker save $DOCKER_NAME -o /tmp/docker_image.tar
    - persist_to_workspace:
        root: /tmp
        paths:
        - docker_image.tar
  
  deploy_dev_cc:
    docker:
    - image: docker:17.05.0-ce-git
    steps:
    - add_ssh_keys:
        fingerprints:
        - 5a:4b:ef:15:70:14:a6:a1:0d:ca:4c:b8:e0:dd:a4:7d
    - attach_workspace:
        at: /tmp/workspace
    - run:
        name: Push singularity image to compute canada
        no_output_timeout: 1h
        command: |
          ssh-keyscan $CC_HOST >> ~/.ssh/known_hosts
          if [ "$CIRCLE_BRANCH" = "master" ]; then MY_TAG=latest; else MY_TAG=$CIRCLE_BRANCH; fi
          scp /tmp/workspace/singularity_image.sif ${CC_USER}@${CC_HOST}:${CC_PATH}/${CIRCLE_PROJECT_USERNAME}_${CIRCLE_PROJECT_REPONAME}_${MY_TAG}.sif
  
  deploy_dev:
    docker:
    - image: docker:17.05.0-ce-git
    steps:
    - setup_remote_docker
    - attach_workspace:
        at: /tmp/workspace
    - run:
        name: Load docker image
        no_output_timeout: 1h
        command: |
          docker load -i /tmp/workspace/docker_image.tar
    - run:
        name: Pushing build to docker hub
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          if [ "$CIRCLE_BRANCH" = "master" ]; then MY_TAG=latest; else MY_TAG=$CIRCLE_BRANCH; fi
          export DOCKER_NAME=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$MY_TAG
          # tag and push here:
          echo docker push $DOCKER_NAME
          docker push $DOCKER_NAME
  
  deploy_release:
    docker:
    - image: docker:17.05.0-ce-git
    steps:
    - setup_remote_docker
    - attach_workspace:
        at: /tmp/workspace
    - run:
        name: Load docker image
        no_output_timeout: 1h
        command: |
          docker load -i /tmp/workspace/docker_image.tar
    - run:
        name: Pushing build to docker hub
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          export DOCKER_NAME=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest
          export DOCKER_RELEASE=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG
          # tag and push here:
          echo docker tag $DOCKER_NAME $DOCKER_RELEASE
          docker tag $DOCKER_NAME $DOCKER_RELEASE
          docker push $DOCKER_RELEASE
          docker push $DOCKER_NAME
          
  deploy_release_cc:
    docker:
    - image: docker:17.05.0-ce-git
    steps:
    - add_ssh_keys:
        fingerprints:
        - 5a:4b:ef:15:70:14:a6:a1:0d:ca:4c:b8:e0:dd:a4:7d
    - attach_workspace:
        at: /tmp/workspace
    - run:
        name: Push singularity image to compute canada
        no_output_timeout: 1h
        command: |
          ssh-keyscan $CC_HOST >> ~/.ssh/known_hosts
          scp /tmp/workspace/singularity_image.sif ${CC_USER}@${CC_HOST}:${CC_PATH}/${CIRCLE_PROJECT_USERNAME}_${CIRCLE_PROJECT_REPONAME}_${CIRCLE_TAG}.sif


        
workflows:
  version: 2
  commit:
    jobs:    
    - build_docker:
        filters:
          tags:
            only: /.*/
        context: org-global
    - build_sif:
        filters:
          tags:
            only: /.*/
        context: org-global
        requires:
        - build_docker
#uncomment if there are tests defined
#    - test_sif:
#        filters:
#          tags:
#            only: /.*/
#        context: org-global
#        requires:
#        - build_sif
    - deploy_dev_cc:
        filters:
          tags:
            ignore: /^v.*/
        requires:
        - build_sif
#        - test_sif
        context: org-global
    - deploy_dev:
        filters:
          tags:
            ignore: /^v.*/
        requires:
        - build_docker
#        - test_sif 
        context: org-global
    - deploy_release:
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
        requires:
        - build_docker
#        - test_sif
        context: org-global
    - deploy_release_cc:
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
        requires:
        - build_sif
#        - test_sif
        context: org-global

